### ISSUE TITLE
Towards a v1.0.0 release.

### ISSUE THREAD

**Issue by ChadSikorra** [FreeDSx/LDAP#50]
I would like to release a v1.0.0 version of this library, as it has been getting many 0.x.0 releases and I haven't really defined what a 1.0.0 type of release would need. The main things I think need to happen are:

* Drop support for EOL versions of PHP. The older versions of this library will have to suffice for those that need it. This would effectively bump the library to PHP 7.4.
* Add a more fluent search builder class. This would mostly be a wrapper around the existing LdapClient with some additional convenience. Currently, building up some searches can still be awkward in code with the methods currently provided.
* Support client-side RFC4533. This seems largely OpenLDAP specific for directory synchronization. This library already supports a client for AD specific directory synchronization, so adding this would be good to even it out.

## TODO

- [ ] Bump the PHP version to ~~8.1~~ 8.2.
- [x] Add proper types, return types, and use strict_types throughout the codebase.
- [x] Use Options objects instead of arrays for the `LdapClient` and `LdapServer`.
  - [x] Verify client-side referral chasing works as expected after the options changes.
  - [x] Update documentation related to options.
- [x] Add a more fluid search builder.
- [x] Support client-side RFC4533 for interacting with directory synchronization.
  - [x] Verify the `poll` logic is implemented properly for content updates. Needs integration tests. 
- [x] Support faster search result processing via anonymous functions instead of waiting for a complete result set to be returned.
  - [x] Update documentation to demonstrate this new usage in searching. 
- [x] Add an extensible LDAP server backend storage system.
  - [x] Decouple the authentication system from the general backend.
  - [x] Decouple general paging handling from the backend.
  - [x] Decouple bind name resolution and make it configurable.
  - [x] Add a JSON file based storage adapter.
  - [x] Add an in-memory based storage adapter.
  - [x] Investigate potential sqlite / pdo based adapter.
  - [x] Add load test to CI for server backends / storage adapters (testing concurrent load).
  - [ ] Final security validations / finalization of new backend API.
- [x] Support canceling sync / search requests in the client. 
- [x] Add an upgrade guide for changes:
  - [x] Options changes from array to objects.
  - [x] Server request handlers only support object instances now.
  - [x] Server request handlers for searching must return a `SearchResult` object. 
  - [x] Making a server proxy instance uses options objects now.
- [ ] Prepare all branches for a 1.0 release.
  - [ ] Pin all FreeDSx libraries with a final pre-1.0 tag bump that tightens current deps.
  - [ ] Create 1.0 branches on sasl / socket / asn1, bump deps / other cleanup.
  - [ ] Rename master to 0.x-maintenance across projects, flip 1.0 to master.
  - [ ] Tag 1.0 on dependent projects so it can be used here on the new master.
  - [ ] Tag final 1.0 here once everything else is complete.

**Comment by davidbuzz** [comment]
implement  a complete server?

**Comment by ChadSikorra** [comment]
> implement a complete server?

It will likely continue to be a limited server component, unfortunately. Though I would like to add support for server side sorting, maybe some other controls

The big issue with a complete server is the backend storage implementation, which I'm not super familiar with in general.

**Comment by davidbuzz** [comment]
> The big issue with a complete server is the backend storage implementation, which I'm not super familiar with in general.

OpenLDAP has a few "backends" - such as MDB - which is just a in-memory storage,  BDB which is a simple embedded database a bit like sqlite, but to be honest as a proof-of-concept in native php it doesn't need to be fast/quick/good, so it could just as easily be a big in-ram object/array/list-of-lists kinda thing, optionally persisted-to-disk [or database] using serialize() / unserialize()  as a first try.   It could alternatively just be stored on-disk as one or more json file/s or something.  

ref: https://www.openldap.org/doc/admin24/backends.html

**Comment by ChadSikorra** [comment]
I want to finish up the outstanding work for a final release here. However, it might not happen until closer towards the end of the year. I'm currently looking for a job and that is taking priority over this for the time being.

**Comment by ChadSikorra** [comment]
Job search is complete...but now the opposite problem is all my time being taken up by work 😢 Still hope to complete this one way or another.

**Comment by Lappihuan** [comment]
@ChadSikorra is there any way we can help push this over the finish line?

**Comment by ChadSikorra** [comment]
> @ChadSikorra is there any way we can help push this over the finish line?

Hello! There's only a few things left for this. The main one is that I don't think I implemented the SyncRepl client completely correctly on the 1.0 branch, and I haven't had the time to investigate / test / fix. I could maybe just mark that as experimental, and I'm certainly open to PRs to fix the implementation.

Beyond that, it's just some minor cleanup tasks I guess. It's been on my mind to finish this, but between work and my personal life I've been strapped for time to actually finish it.

**Comment by ChadSikorra** [comment]
This is very very close to being wrapped up. The last thing I'm tackling is a pattern for better handling storage in the server component (at least giving options / extensibility and reorganizing the existing code). There's really only testing and some refinement to go.

**Comment by ChadSikorra** [comment]
I went down a very large rabbit hole refactoring the server component to support different backend storage (pdo, file, memory). It opened up a bunch of new functionality.

Still trying to wrap it up, but the LDAP server is way more complete from an RFC perspective at this point. I've also updated the dependent libraries. So still making good progress on this.
